### ISSUE TITLE
Frozen Cows

### ISSUE THREAD

**Issue by GalaxyWolf777** [IntricaciesOfSociety/CowSocietySimulation#57]
when left running for about  2 or 3 in-game days, I found out that there is a large number of cows who just constantly spin and never left the area where they had first spawned at in the initial startup of the game. the number decreases significantly when the hotel is completely finished but there are still some cows that are still stuck spinning. the 2 images I put on here show cows that have not moved for almost 3 days
![screen shot 2019-02-11 at 1 59 15 pm](https://user-images.githubusercontent.com/46492469/52590429-de8d6280-2e06-11e9-95c2-53fcaffde52b.png)
![screen shot 2019-02-11 at 2 01 29 pm](https://user-images.githubusercontent.com/46492469/52590431-de8d6280-2e06-11e9-9438-cb2db7963f89.png)

**Comment by NotZack** [comment]
Caused by a lack of resources and cows doing jobs that they cannot complete.
